### ISSUE TITLE
ErrorException thrown when open_basedir restriction in effect

### ISSUE THREAD

**Issue by twouters** [nystudio107/craft-twigpack#73]
https://github.com/nystudio107/craft-twigpack/blob/53d8eb90a72c4fa9e7a907a943a15ab0ea6d90cd/src/helpers/Manifest.php#L287

An exception is thrown when open_basedir is enabled when checking if a module URI is a filesystem path.
Instead of an exception, it could act as if `is_file()` returns false.

**Comment by twouters** [comment]
```
2021-07-01 18:56:30 [-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: is_file(): open_basedir restriction in effect. File(/dist/main.81dc9bdb52d04dc20036.css) is not within the allowed path(s): (/var/www:/tmp) in /var/www/vendor/nystudio107/craft-twigpack/src/helpers/Manifest.php:287
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 /var/www/vendor/nystudio107/craft-twigpack/src/helpers/Manifest.php(287): is_file()
#3 /var/www/vendor/nystudio107/craft-twigpack/src/helpers/Manifest.php(84): nystudio107\twigpack\helpers\Manifest::getModule()
#4 /var/www/vendor/nystudio107/craft-twigpack/src/services/Manifest.php(49): nystudio107\twigpack\helpers\Manifest::getCssModuleTags()
#5 /var/www/vendor/nystudio107/craft-twigpack/src/variables/ManifestVariable.php(56): nystudio107\twigpack\services\Manifest->getCssModuleTags()
#6 /var/www/vendor/twig/twig/src/Extension/CoreExtension.php(1511): nystudio107\twigpack\variables\ManifestVariable->includeCssModule()
#7 /var/www/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#8 /var/www/storage/runtime/compiled_templates/a8/a854d3c2ce39cbb2dc472fee5f7292337b363483c040ecb23e5a8ec789aa4a02.php(112): craft\helpers\Template::attribute()
#9 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0f30ed6966205482254fada78e04cae4608e2b11b3cf6a22fe8c3eab1975f5cc->doDisplay()
#10 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#11 /var/www/storage/runtime/compiled_templates/14/14c2e569891a0db362388ca04b7bea4f603a8bbd070e83d5466b306edec161d2.php(46): Twig\Template->display()
#12 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_726decf4787cd0aab224ecce3062830235dd616f1093cb1864faba915ddf71e5->doDisplay()
#13 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#14 /var/www/storage/runtime/compiled_templates/8b/8b10ec7cfdbde8df767cba49d6d7ab8a742a53a93ddf4aa86eba44eacc441a34.php(38): Twig\Template->display()
#15 /var/www/vendor/twig/twig/src/Template.php(405): __TwigTemplate_edaed59ed623c416dbcb500f132521f3f28f1774827cdbb49fbc177991d630b0->doDisplay()
#16 /var/www/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#17 /var/www/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#18 /var/www/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#19 /var/www/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#20 /var/www/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render()
#21 /var/www/vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate()
#22 /var/www/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate()
#23 /var/www/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate()
#24 [internal function]: craft\controllers\TemplatesController->actionRender()
#25 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#26 /var/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#27 /var/www/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#28 /var/www/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#29 /var/www/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction()
#30 /var/www/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#31 /var/www/vendor/craftcms/cms/src/web/Application.php(263): yii\web\Application->handleRequest()
#32 /var/www/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#33 /var/www/www/index.php(21): yii\base\Application->run()
#34 {main}
```

This is on php 7.4.21

**Comment by khalwat** [comment]
Sounds like maybe your paths aren't setup right? Not sure why it should be looking in `/` -> `/dist/main.81dc9bdb52d04dc20036.css`

You probably don't have the `server` and/or `devServer` URLs set up properly: https://github.com/nystudio107/craft-twigpack/blob/v1/src/config.php#L44

**Comment by twouters** [comment]
It works after changing `publicPath` to `@web` instead of `/`.  
I'll have to validate with an older php version, the issue has been reported to me after we've updated to the latest release.

**Comment by twouters** [comment]
Will reopen if needed.

**Comment by twouters** [comment]
FYI, it looks like this change is causing restrictions where it didn't in older php versions:
https://github.com/php/php-src/commit/ee7a8acde929d47362077a8d54eab4e0c331b7a3#diff-c6b4b3bd0219de9532089b76f62110395b6438b1f388ca9f3ad2d9340751adc1
On 01 Jul 2021 20:06, Andrew Welch ***@***.***> wrote:


Sounds like maybe your paths aren't setup right? Not sure why it should be looking in `/` -> `/dist/main.81dc9bdb52d04dc20036.css`

You probably don't have the `server` and/or `devServer` URLs set up properly: https://github.com/nystudio107/craft-twigpack/blob/v1/src/config.php#L44

**Comment by davidhellmann** [comment]
Same problem here. But the change to @web works.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-twigpack/commit/116b8540f51cd65273097a513e354a781afacdcf
